name: long_sang_s_application
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter:   # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
    sdk: flutter # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
  flutter_localizations: 
    sdk: flutter
  flutter_svg: ^2.0.12
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  connectivity_plus: ^6.1.0
  gradient_borders: ^1.0.2
  flutter_riverpod: ^2.5.1
  equatable: ^2.0.5
  # Backend Integration Dependencies
  supabase_flutter: ^2.5.6
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  # Local Storage & State Management
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  riverpod_annotation: ^2.3.5
dev_dependencies: 
  flutter_test:    # 🚨 CRITICAL: Required for Flutter project testing - DO NOT REMOVE
    sdk: flutter    # 🚨 CRITICAL: Required for Flutter project testing - DO NOT REMOVE
  # Code Generation
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1
flutter: 
  uses-material-design: true # 🚨 CRITICAL: Required for Material icon font - DO NOT REMOVE
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: ABeeZee
      fonts: 
        - asset: assets/fonts/ABeeZeeRegular.ttf
          weight: 400
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoSemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoBold.ttf
          weight: 700
    - family: Alumni Sans
      fonts: 
        - asset: assets/fonts/AlumniSansBlack.ttf
          weight: 900
    - family: Acme
      fonts: 
        - asset: assets/fonts/AcmeRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Rambla
      fonts: 
        - asset: assets/fonts/RamblaRegular.ttf
          weight: 400
    - family: Agdasima
      fonts: 
        - asset: assets/fonts/AgdasimaRegular.ttf
          weight: 400

  # 🚨 CRITICAL ASSET MANAGEMENT RULES:
  # - DO NOT ADD NEW ASSET DIRECTORIES (assets/svg/, assets/icons/, etc.)
  # - ONLY USE EXISTING AND ITEMS AVAILABLE IN THE DIRECTORIES LISTED ABOVE (assets/, assets/images/)

  # 🚨 CRITICAL FONTS RULE:
  # - DO NOT ADD NEW LOCAL FONTS TO assets/fonts/ 
  # - ONLY USE EXISTING LOCAL FONTS FROM assets/fonts/